### PR TITLE
Support passing archive entry timestamp

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
cc @cstamas

**Comment by jvanzyl** [comment]
Can you explain more what you want and why the built in normalized timestamp doesn’t work?

**Comment by jvanzyl** [comment]
You understand that if you do two builds, 2 minutes apart, if the zip entries have different timestamps the checksums of the zip you build will different. This notion of the zip time entry was originally taken from Bazel, specifically for idempotent builds.

**Comment by wendigo** [comment]
@jvanzyl I want to support reproducible builds in provisio plugin. Hence I was thinking to pass `project.build.outputTimestamp` to the provision and to the archiver

**Comment by wendigo** [comment]
@jvanzyl ptal here: https://github.com/jvanzyl/provisio/pull/88

**Comment by cstamas** [comment]
I believe goal is that when "normalize" to have all archive entries same TS, unlike today, when in case of "normalize" each entry will have own "system current millis" TS.

**Review by cstamas — APPROVED** [review]

**Comment by jvanzyl** [comment]
@wendigo when the `normalize` option is used then all then the same timestamp applied is the same. Just making sure we are talking about the same thing. What you are proposing will make the build non-reprodicible unless I'm misunderstanding. You can't change the timestamp on the zip entries and have the outer checksum of the artifact be the same from build to build.

https://github.com/jvanzyl/provisio-archiver/blob/master/src/main/java/ca/vanzyl/provisio/archive/Archiver.java#L44

https://github.com/jvanzyl/provisio-archiver/blob/master/src/main/java/ca/vanzyl/provisio/archive/Archiver.java#L155

You either want normalized time entries or you don't. Making this configurable just leaves it open to misconfiguration. Someone intends to leave it the same on the branch, but changes it, or misconfigures it, or something changes in Maven and now in the worst of times you can’t tell if the build is idempotent without checking every resource in the JAR. 

I don't really see the value in making this configurable. cc @cstamas

**Comment by cstamas** [comment]
Agreed with @jvanzyl 

Problem of provisio is that it does NOT enable "normalization" at all, so it uses _real timestamps_ of files being archived, and if any of those are not reproducible, resulting archive is not either.

**Pull request closed without merging**
